spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotlight_db
    username: fredericksamanga
    password: samanga124
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update




server:
  port: 8080
