version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: spotlight-postgres
    environment:
      POSTGRES_USER: fredericksamanga
      POSTGRES_PASSWORD: samanga124
      POSTGRES_DB: spotlight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: