package com.jexpression.spotlightzim.model;

public enum SocialMediaHandles {

    TWITTER, INSTAGRAM, FACEBOOK, YOUTUBE, TIKTOK, SNAPCHAT,
    LINKEDIN, PINTEREST, REDDIT, TUMBLR, WHATSAPP, TELEGRAM,
    DISCORD, VIBER, SKYPE, VINE, PERISCOPE, FLICKR, YELP, QUORA,
    MEDIUM, BEHANCE, DRIBBBLE, SOUND_CLOUD, MIXCLOUD, CLUBHOUSE,
    PATREON, TUNE_IN, SPOTIFY, TIDAL, DEEZER, BANDCAMP, PODOB,
    STUMBLR, LIVEJOURNAL, MYSPACE, VERO, WECHAT, KIK, LINE, WEIBO,
    QQ, MEEWE, PEACH, GOOGLE_PLUS, FOURSQUARE, BLOGGER, WEEBLY,
    WORDPRESS, BLOGSPOT, SUBSTACK, GAB, MINDS, PARLER
}
